# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

# Usage documentation: build_charm.md
---
name: "Charmed Kafka Setup"
description: "Creates a Kafka deployment for integration testing"
author: "Canonical"

branding:
  icon: "alert-circle"
  color: "purple"

inputs:
  broker-units:
    description: Number of Kafka broker to be used
    default: "1"
    required: false
  zookeeper-units:
    description: Number of ZooKeeper servers to be used
    default: "1"
    required: false

outputs:
  bootstrap-server:
    description: Address for the bootstrap server to be used
    value: ${{ steps.get-metadata.outputs.bootstrap-server }}

runs:
  using: composite
  steps:
    - name: 🏗 Checkout Kafka kraft repo
      uses: actions/checkout@v4
      with:
        repository: deusebio/setup-kafka-action
        path: "kafka"

    - name: Setup operator environment
      # TODO: Replace with custom image on self-hosted runner
      uses: charmed-kubernetes/actions-operator@main
      with:
        provider: lxd
        juju-channel: 3.4/stable
        bootstrap-options: "--agent-version 3.4.2"

    - name: Deploy Kafka
      id: deploy
      working-directory: "kafka"
      shell: bash
      run: |
        juju add-model kafka
        juju deploy ./resources/bundle.yaml
        juju wait-for application kafka --query='name=="kafka" && (status=="active" || status=="idle")'
        juju wait-for application admin --query='name=="admin" && (status=="active" || status=="idle")'

    - name: Fetch metadata
      id: get-metadata
      shell: bash
      run: |
        juju run admin/leader get-credentials --format yaml > metadata.yaml
        echo "bootstrap-server=my-test" >> $GITHUB_OUTPUT
        echo "username=$(yq '.username' metadata.yaml)" >> $GITHUB_OUTPUT
        echo "password=$(yq '.password' metadata.yaml)" >> $GITHUB_OUTPUT
