# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install yamllint
        run: python3 -m pip install yamllint
      - name: YAML Lint
        run:  |
          yamllint -d "{extends: relaxed, rules: {line-length: {max: 250}}}" \
            --no-warnings action.yaml

#   lxd:
#     runs-on: ubuntu-22.04
#     timeout-minutes: 30
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           path: setup-kafka-action
#
#       - name: Setup Kafka
#         id: kafka
#         uses: ./setup-kafka-action
#         with:
#           zookeeper-units: 1
#           broker-units: 1
#
#       - name: Show Juju status
#         run: |
#           juju status
#
#       - name: Check metadata
#         run: |
#           echo "Endpoint: ${{ steps.kafka.outputs.bootstrap-server }}"
#           echo "Username: ${{ steps.kafka.outputs.username }}"
#           echo "Password: ${{ steps.kafka.outputs.password }}"
#           echo "CA: ${{ steps.kafka.outputs.ca-certificate }}"
#
#   tls:
#     runs-on: ubuntu-22.04
#     timeout-minutes: 30
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           path: setup-kafka-action
#
#       - name: Setup Kafka TLS
#         id: kafka
#         uses: ./setup-kafka-action
#         with:
#           zookeeper-units: 1
#           broker-units: 1
#           encryption: true
#
#       - name: Show Juju status
#         run: |
#           juju status
#
#       - name: Check metadata
#         run: |
#           echo "Endpoint: ${{ steps.kafka.outputs.bootstrap-server }}"
#           echo "Username: ${{ steps.kafka.outputs.username }}"
#           echo "Password: ${{ steps.kafka.outputs.password }}"
#           echo "CA: ${{ steps.kafka.outputs.ca-certificate }}"

  microk8s:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: setup-kafka-action

      - name: Setup Kafka TLS
        id: kafka
        uses: ./setup-kafka-action
        with:
          zookeeper-units: 1
          broker-units: 1
          substrate: microk8s

      - name: Show Juju status
        run: |
          juju status

      - name: Check metadata
        run: |
          echo "Endpoint: ${{ steps.kafka.outputs.bootstrap-server }}"
          echo "Username: ${{ steps.kafka.outputs.username }}"
          echo "Password: ${{ steps.kafka.outputs.password }}"
          echo "CA: ${{ steps.kafka.outputs.ca-certificate }}"